name = "ntfy-cf-api"
main = "worker/src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

account_id = "28970b96b4880e4f41cc0487104898a0"

[[d1_databases]]
binding = "DB"
database_name = "ntfy-cf-db"
database_id = "32d34caf-a618-41d0-9ce0-213c9e8ef090"

[[durable_objects.bindings]]
name = "TOPIC_DO"
class_name = "TopicDO"

[[migrations]]
tag = "v1"
new_classes = ["TopicDO"]

[vars]
BASE_URL = "https://ntfy-cf-api.finchtech.my.workers.dev"
ENABLE_SIGNUP = "true"
ENABLE_LOGIN = "true"
DISALLOWED_TOPICS = "docs,static,file,app,metrics,account,settings,signup,login,v1"
ACCESS_CONTROL_ALLOW_ORIGIN = "*"
VISITOR_SUBSCRIPTION_LIMIT = "30"
VISITOR_MESSAGE_DAILY_LIMIT = "0"
MESSAGE_SIZE_LIMIT = "4096"
KEEPALIVE_INTERVAL = "45"
